#!/bin/bash

user_desktop=`xdg-user-dir DESKTOP`
user_desktop_file="$user_desktop/turan-mycomputer.desktop"
root_desktop_file="/usr/share/applications/turan-mycomputer.desktop"

config_dir="$HOME/.config/turan-mycomputer/"
config_file="$config_dir/desktop"


if ! [[ -f "$config_file" ]]; then
	if ! [[ -d "$config_dir" ]]; then
		mkdir -p "$config_dir"
	fi

	if ! [[ -f "$user_desktop_file" ]]; then
		if [[ -f "$root_desktop_file" ]]; then
			if [[ -d "$user_desktop" ]]; then
				cp "$root_desktop_file" "$user_desktop_file"
				chmod +x "$user_desktop_file"
				gio set "$user_desktop_file" "metadata::trusted" true
			fi
		fi
	fi
	date "+%s" > "$config_file"
fi

exit 0
